
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'bryaalbani/app_frontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
